[package]
name = "gob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.14"
ulid = "1.1.2"
crc32fast = "1.4.2"

[dependencies.serde]
version = "1.0.204"
features = ["derive"]
